/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cdbm_ant;

import calendar.FechaSesion;
import cinesdbmanager.Context.AppConfig;
import cinesdbmanager.Modelo.Cine;
import cinesdbmanager.Modelo.Pelicula;
import cinesdbmanager.Modelo.Sala;
import cinesdbmanager.Modelo.Sesion;

import javax.swing.*;
import java.awt.Color;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author danie
 */
public class CreateGUI extends javax.swing.JFrame {

    String entidad; //screen
    String idCineFK = null; // Clave ajena
    String idSalaFK = null; // Clave ajena
    Interfaz gui; // Mantener la interfaz anterior
    /**
     * Creates new form CreateGUI
     */
    public CreateGUI() {
        initComponents();
    }
    
    //Constructor para Cines
    public CreateGUI(Interfaz gui, String entidad, String label1, String label2) {
        this.gui = gui;
        initComponents();
        lblData1.setText(label1);
        lblData2.setText(label2);
        lblData3.setVisible(false);
        tfData3.setVisible(false);
        lblData4.setVisible(false);
        cbVIP.setVisible(false);
        datePick.setVisible(false);
        timePanel.setVisible(false);
        cbxPeliculas.setVisible(false);
        this.entidad = entidad;
        lblGenericMsg.setText(("Añadir " + entidad).toUpperCase());
        this.getContentPane().setBackground(new Color(255,204,95));
    }
    
    //Constructor para Salas
    public CreateGUI(Interfaz gui, String entidad,String label1, String label2, String label3, String cineFK) {
        this.gui = gui;
        initComponents();
        lblData1.setText(label1);
        lblData2.setText(label2);
        lblData3.setText(label3);
        lblData4.setVisible(false);
        tfData2.setVisible(false);
        cbVIP.setVisible(true);
        datePick.setVisible(false);
        timePanel.setVisible(false);
        cbxPeliculas.setVisible(false);
        idCineFK = cineFK;
        this.entidad=entidad;
        lblGenericMsg.setText(("Añadir " + entidad).toUpperCase());
        this.getContentPane().setBackground(new Color(255,204,95));
    }
    
    //Constructor para Sesiones
    public CreateGUI(Interfaz gui, String entidad,String label1, String label2, String label3, String cineFK, String salaFK) {
        this.gui = gui;
        initComponents();
        lblData1.setText(label1);
        lblData2.setText(label2);
        lblData3.setText(label3);
        cbVIP.setVisible(false);
        datePick.setVisible(true);
        timePanel.setVisible(true);
        tfData2.setVisible(false);
        tfData3.setVisible(false);
        lblData4.setText("Pelicula");
        cbxPeliculas.setVisible(true);
        cargarPeliculas();
        idCineFK = cineFK;
        idSalaFK = salaFK;
        this.entidad=entidad;
        lblGenericMsg.setText(("Añadir " + entidad).toUpperCase());
        this.getContentPane().setBackground(new Color(255,204,95));
    }
    
    //Constructor para peliculas
    public CreateGUI(Interfaz gui, String entidad,String label1, String label2, String label3) {
        this.gui = gui;
        initComponents();
        lblData1.setText(label1);
        lblData2.setText(label2);
        lblData3.setText(label3);
        lblData4.setVisible(false);
        cbVIP.setVisible(false);
        datePick.setVisible(false);
        timePanel.setVisible(false);
        cbxPeliculas.setVisible(false);
        this.entidad=entidad;
        lblGenericMsg.setText(("Añadir " + entidad).toUpperCase());
        this.getContentPane().setBackground(new Color(255,204,95));
    }

    // Guardar la fecha con el jDateChooser
    public FechaSesion getValue(){
        Calendar calendar = datePick.getJCalendar().getCalendar();
        int hora = (Integer) horaSpinner.getValue();
        int minuto = (Integer) minutoSpinner.getValue();
        return new FechaSesion(calendar.get(Calendar.DAY_OF_MONTH), calendar.get(Calendar.MONTH),
                calendar.get(Calendar.YEAR),hora, minuto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        tfData1 = new javax.swing.JTextField();
        tfData2 = new javax.swing.JTextField();
        tfData3 = new javax.swing.JTextField();
        lblData1 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        lblData3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        lblGenericMsg = new javax.swing.JLabel();
        cbVIP = new javax.swing.JCheckBox();
        datePick = new com.toedter.calendar.JDateChooser();
        timePanel = new javax.swing.JPanel();
        lbl_Hora = new javax.swing.JLabel();
        horaSpinner = new com.toedter.components.JSpinField();
        lbl_Minuto = new javax.swing.JLabel();
        minutoSpinner = new com.toedter.components.JSpinField();
        cbxPeliculas = new javax.swing.JComboBox<>();
        lblData4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfData1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfData1KeyTyped(evt);
            }
        });

        tfData2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfData2KeyTyped(evt);
            }
        });

        tfData3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfData3KeyTyped(evt);
            }
        });

        lblData1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData1.setForeground(new java.awt.Color(83, 60, 65));
        lblData1.setText("Nombre");

        lblData2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData2.setForeground(new java.awt.Color(83, 60, 65));
        lblData2.setText("lblData2");

        lblData3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData3.setForeground(new java.awt.Color(83, 60, 65));
        lblData3.setText("lblData3");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 60, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CINE DB MANAGER");

        btnCancel.setBackground(new java.awt.Color(83, 60, 65));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(253, 184, 75));
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAccept.setBackground(new java.awt.Color(83, 60, 65));
        btnAccept.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(253, 184, 75));
        btnAccept.setText("AÑADIR");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblGenericMsg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGenericMsg.setForeground(new java.awt.Color(83, 60, 65));
        lblGenericMsg.setText("Añadir elemento");

        timePanel.setBackground(new java.awt.Color(255, 204, 95));

        lbl_Hora.setText("HORA");

        horaSpinner.setBackground(new java.awt.Color(255, 204, 95));
        horaSpinner.setMaximum(23);
        horaSpinner.setMinimum(0);

        lbl_Minuto.setText("MINUTO");

        minutoSpinner.setBackground(new java.awt.Color(255, 204, 95));
        minutoSpinner.setMaximum(59);
        minutoSpinner.setMinimum(0);

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_Minuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Minuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(horaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(minutoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cbxPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeliculasActionPerformed(evt);
            }
        });

        lblData4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData4.setForeground(new java.awt.Color(83, 60, 65));
        lblData4.setText("lblData4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGenericMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblData1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblData2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblData3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblData4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfData1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfData3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(datePick, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVIP, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfData2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addComponent(cbxPeliculas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnAccept, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenericMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblData2)
                        .addComponent(cbVIP))
                    .addComponent(datePick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblData3))
                    .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData4))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Volver a la pantalla principal sin guardar

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        // Desaparecer la pantalla
        this.dispose();
        gui.setVisible(true);
        System.out.println("Cancelado");
    }//GEN-LAST:event_btnCancelActionPerformed

    // Crear la nueva instancia de la entidad y volver a la pantalla principal
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        // Llamar a crear con los datos
        switch (entidad) {
            case "cine":
                añadirCine();
                break;
            case "sala":
                añadirSala();
                break;
            case "sesion":
                añadirSesion();
                break;
            case "pelicula":
                añadirPelicula();
                break;
            default:
                System.err.println("Error al insertar");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    // Tipado del texto de entrada y límite de carácteres
    private void tfData1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData1KeyTyped
        // TODO add your handling code here:
        // Comenta
        char caracter = evt.getKeyChar();
        if("sala".equals(entidad)){
            if (!Character.isDigit(caracter)) {
                evt.consume();
            }
        }else if("sesion".equals(entidad)){
            if (!Character.isDigit(caracter) && caracter != '.' || (tfData1.getText().length() >= 25)
                    || (tfData1.getText().contains(".") && caracter == '.')) {
                evt.consume();
            }
        }else if("cine".equals(entidad)){
            if (tfData1.getText().length() >= 25) {
                evt.consume();
            }
        }else if("peliculas".equals(entidad)){
             if (tfData1.getText().length() >= 25) {
                evt.consume();
            }
        } 
    }//GEN-LAST:event_tfData1KeyTyped

    private void tfData3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData3KeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if("sala".equals(entidad)){
            if (!Character.isDigit(caracter)) {
                evt.consume();
            }
        }else if("pelicula".equals(entidad)){
            if (!Character.isDigit(caracter)) {
                evt.consume();
            }
        }
        
    }//GEN-LAST:event_tfData3KeyTyped

    private void cbxPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeliculasActionPerformed

    private void tfData2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData2KeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        if("cine".equals(entidad)){
            if (tfData2.getText().length() >= 50) {
                evt.consume();
            }
        }else if("peliculas".equals(entidad)){
             if (tfData2.getText().length() >= 25) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfData2KeyTyped
    
    // Creación de instancias
    private void añadirPelicula(){
        if(!tfData1.getText().isEmpty() && !tfData2.getText().isEmpty() && !tfData3.getText().isEmpty()) {
            Pelicula pelicula = new Pelicula(tfData1.getText(), tfData2.getText(), Integer.parseInt(tfData3.getText()));
            AppConfig.getPeliculaServicio().insertarPelicula(pelicula);
            this.dispose();
            gui.cargarTabla();
            gui.setVisible(true);
            System.out.println("Nueva pelicula insertada");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.",
                    "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void añadirSala(){
        if(!tfData3.getText().isEmpty() && !tfData1.getText().isEmpty()) {
            Sala sala = new Sala(Integer.valueOf(tfData3.getText()),
                    Integer.valueOf(tfData1.getText()), cbVIP.isSelected(), Integer.parseInt(idCineFK));
            AppConfig.getSalaServicio().insertarSala(sala);
            this.dispose();
            gui.cargarTabla();
            gui.setVisible(true);
            System.out.println("Nueva sala insertada");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.",
                    "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void añadirCine(){
        if (!tfData1.getText().isEmpty() && !tfData2.getText().isEmpty()){
            Cine cine = new Cine(tfData2.getText(), tfData1.getText());
            AppConfig.getCineServicio().insertarCine(cine);
            this.dispose();
            gui.cargarTabla();
            gui.setVisible(true);
            System.out.println("Nuevo cine insertado");
        }else {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.",
                    "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void añadirSesion(){
        if (!tfData1.getText().isEmpty() && cbxPeliculas.getSelectedItem()!=null) {
            Sala sala1 = AppConfig.getSalaServicio().buscarSalaporIds(Integer.parseInt(idCineFK), 
                    Integer.parseInt(idSalaFK));
            FechaSesion fecha = new FechaSesion();
            fecha = getValue();
            System.out.println(fecha.toString());
            Sesion sesion = new Sesion(fecha.getDate(), fecha.getTime(), Double.parseDouble(tfData1.getText()));
            sesion.setSalaByIdSala(sala1);
            sesion.setPeliculaByIdPelicula((Pelicula) cbxPeliculas.getSelectedItem());
            //sesion.setPeliculaByIdPelicula(AppConfig.getPeliculaServicio().buscarPelicula(AppConfig.getPeliculaServicio().idPeliculaMaximo()));
            AppConfig.getSesionServicio().insertSesion(sesion);
            this.dispose();
            gui.cargarTabla();
            gui.setVisible(true);
            System.out.println("Nueva sesion insertada");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", 
                    "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarPeliculas(){
        ArrayList<Pelicula>peliculas= (ArrayList<Pelicula>) AppConfig.getPeliculaServicio().listarTodo();
        peliculas.forEach(p -> {
            cbxPeliculas.addItem(p);
        });
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JCheckBox cbVIP;
    private javax.swing.JComboBox<Pelicula> cbxPeliculas;
    private com.toedter.calendar.JDateChooser datePick;
    private com.toedter.components.JSpinField horaSpinner;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JLabel lblData4;
    private javax.swing.JLabel lblGenericMsg;
    private javax.swing.JLabel lbl_Hora;
    private javax.swing.JLabel lbl_Minuto;
    private com.toedter.components.JSpinField minutoSpinner;
    private javax.swing.JTextField tfData1;
    private javax.swing.JTextField tfData2;
    private javax.swing.JTextField tfData3;
    private javax.swing.JPanel timePanel;
    // End of variables declaration//GEN-END:variables
}
